#!/usr/bin/env bash
# script for configuring HAProxy load balancer server

sudo apt-get update -y
sudo apt-get install haproxy -y

server_config=\
"
frontend  haproxynode
        bind *:80
        mode http
        default_backend backendnodes
backend  backendnodes
        balance roundrobin
        mode http
	server 264687-web-01 34.227.92.219:80 check
        server 264687-web-02 54.236.50.82:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
