#!/usr/bin/env bash
# This script sets up custom IP address resolutions and is designed to work within a Docker environment.
cp /etc/hosts ~/hosts.new
echo '127.0.0.2 localhost' >> ~/hosts.new
echo '8.8.8.8 facebook' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
